### ISSUE TITLE
CNC pilot version 1.55

### ISSUE THREAD

**Issue by miranmn** [martin2250/OpenCNCPilot#103]
Hi, Can you tell me if this version 1.55 of CNC pilot, will work with USB control board GRBL
version 1.1 j ?

**Comment by martin2250** [comment]
There is no grbl version 1.1j. The latest release is 1.1f. I don't test compatibility with other versions of grbl, so you'll have to try it out.

**Comment by miranmn** [comment]
Hi, thanks for the feedback, but look the following link to see the board grbl 1.1j
https://www.ebay.com/itm/GRBL-1-1-J-USB-port-cnc-engraving-machine-control-board-3-axis-control-laser/254043095018?hash=item3b2625ffea:g:ZHQAAOSwXI1cJkxP&frcectupt=true
I am thinking to buy it to replace my old 0.9.15 board!

**Comment by martin2250** [comment]
Idk about the board. If it still works just update the firmware on your old one. grbl 1.1j does not exist (yet), maybe the ebay seller modified it?
