### ISSUE TITLE
Probe Failure. Not in expected initial state...

### ISSUE THREAD

**Issue by drdty** [martin2250/OpenCNCPilot#108]
Hello,

I'm having trouble with the probe mapping. I keep getting the failure mode: "Probe fail. Probe is not in expected initial state before starting probe cycle when G38.2 and G38.3 is not triggered and G38.4 and G38.5 is triggered".

Not to sure what that means....

Thanks for the help and thanks for making the program

Best Regards

![problem1 cnc](https://user-images.githubusercontent.com/50411612/57379522-117c9380-7175-11e9-9395-ca43bac4014b.PNG)

**Comment by martin2250** [comment]
This is not specific to OpenCNCPilot, it's an error reported by grbl.
You'll find your answer here: http://bfy.tw/NZfA

**Comment by deHarro** [comment]
Nice sort of hint :-)
Harald
Did you do that on your own?
Harald

**Comment by drdty** [comment]
thanks guys. First time doing anything like this..appreciate the help

**Comment by martin2250** [comment]
Sorry for the shitty answer, but if the first or second result of googling the error message solves the problem...
Don't take this the wrong way, feel free to ask questions if you're stuck, but do a bit of research first :)

The red text "Probe" at the bottom of the window indicates that the probe input of grbl is triggered, this should help you find the issue with your machine.

@deHarro nope, lmgtfy is a pretty old (well, for my standards at least :sweat_smile: ) service, which is way underappreciated
