### ISSUE TITLE
file dialogs should remember last location

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#11]
to open a file (G-code or hight map)  a standard file open dialog is raised, I can navigate to the file location, select the file and leave the dialog with OK.
When I next will open this very file again, I again have to navigate to the file location.
It will be easier to handle if the program remebers the last folder and proposes this as new starting point.

Just my thoughts about user friedly experience :-)

Harald

**Comment by martin2250** [comment]
Hi Harald,

thanks for the suggestion, I never really noticed, since I usually have everything on my Desktop and use Drag'n'Drop. I'll definitely fix that when I come around to addressing all the issues :)

Martin

**Comment by deHarro** [comment]
Ah, I read that Drag'n'Drop thingy but forgot about it. Will try to get used to it... :-)

**Comment by martin2250** [comment]
So, müsste jetzt funktionieren :)
Grüße, Martin
