### ISSUE TITLE
Limit Z is ignored while surface scan

### ISSUE THREAD

**Issue by salihonur** [martin2250/OpenCNCPilot#110]
Hi,

The machine does homing XYZ properly. Limit-Z is activated when the bit touches to the pcb surface (clean copper). But Z axis isn't pulled back while surface scanning despite the Limit-Z appears in red font on the screen. How can solve this problem?
$21 Hard Limit = 0;

Because otherwise homing isn't done successfully although all limit switches works fine. First it touches and goes a little back and touches again slowly. Same for all XYZ axis.

**Comment by martin2250** [comment]
Hi salihonur,
you need to use the probe input (Arduino Pin A5), not the Z limit switch input, for probing.

**Comment by salihonur** [comment]
Thanks very much Martin. It works properly.
