### ISSUE TITLE
Error in source code

### ISSUE THREAD

**Issue by Northernboy** [martin2250/OpenCNCPilot#119]
Hello Martin,
Is there an error in the source code? Can you please check it. I always do my own little additions but when I download the latest version and compile it before doing my changes I get errors. I'm using Visual Studio 2014.

**Comment by martin2250** [comment]
Hi Northernboy,
try VS 2019 or later. If that doesn't work, please share these errors. There are no commits since the last release, so it should compile as expected.

**Comment by MikeX7** [comment]
Not a code problem, it compiles just fine for me in VS2017

**Comment by Northernboy** [comment]
It’s all good now that I upgraded to VS2019

Thanks
