### ISSUE TITLE
Marlin 1.1.9

### ISSUE THREAD

**Issue by tizi24** [martin2250/OpenCNCPilot#122]
Hi, I find this software fabulous and very interesting to adapt for Marlin 1.1.9 so that we can pcb with our 3D printers

**Comment by tizi24** [comment]
I started to investigate a bit, you can use the "Marlin" G30 code to sense each point of the generated OpenCNCPilot mesh and then apply the different heights of the pcb

**Comment by martin2250** [comment]
Hi @tizi24 

supporting multiple controllers right now would require a lot of changes in the code. Anyways I don't really see the need for this, as pretty much every controller intended for milling uses GRBL (or at least GRBL can be compiled to run on it). If you want to use OpenCNCPilot for your 3D printer, you have two options:
* change the relevant code and maintain a separate fork of this project (not much work, mostly regexes and other string parsing)
* (temporarily) flash GRBL onto your controller

That said, you still need to make sure your 3D printer is rigid enough, mine sure isn't. Do you already have a printer that's modified for milling?
