### ISSUE TITLE
Disconnect is not blocked during a milling job

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#123]
Hi Martin,

I just realized, that disconnecting OCP from GRBL (via button "disconnect") is allowed, even during a running job.
Perhaps you should disable this function during a job?

Luckily I encountered this at my office PC with no real router attached :-) (just an Arduino running GRBL 1.1f)

Harald

**Comment by martin2250** [comment]
Hi Harald,

I'm impressed this bug hasn't been discovered yet, thanks for reporting it!

Martin

**Comment by deHarro** [comment]
You're welcom :-)

**Comment by martin2250** [comment]
Hi Harald,

it's fixed now, along with some other buttons that I apparently forgot. Thanks again!

Martin

**Comment by deHarro** [comment]
Thanks!
Harald
