### ISSUE TITLE
Probing to Z=0 should issue at least a G92 Z0

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#13]
When probing for Z=0 (G38.2 Z-10 F20) one can miss to tell OpenCNCPilot that Z=0 is reached.
This should occur automatically.

Harald

**Comment by martin2250** [comment]
No.
why should it behave in an unexpected way? there are enough reasons to probe without setting zero.
That aside, I think I'll add some configurable macro keys which would allow things like that.

**Comment by martin2250** [comment]
implemented in the latest commit
