### ISSUE TITLE
Upgraded to OPC 1.5.9 and can't turn off the grid?

### ISSUE THREAD

**Issue by happycncer** [martin2250/OpenCNCPilot#135]
Had 1.5.6 up until recently and have now just upgraded to v 1.5.9. On 1.5.6 I had somehow managed to turn off the grid in the viewport somehow - cant remember how now, but it looked a lot cleaner (to me) whist doing small mundane things that didn't take a lot of effort to follow.

Went looking to make 1.5.9 the same and I cannot seem to find where and how I changed it - and I now don't have 1.5.6 to even look at as I deleted it straight after installing v1.5.9.

Can anyone please enlighten me as to exactly how I managed this before - cos I can't find it now!
happycncer

**Comment by deHarro** [comment]
Set "grid thickness" to 0 (Zero) and you're done :-)

![OCP_Viewport_Grid](https://user-images.githubusercontent.com/26298406/83416991-c5f0f380-a421-11ea-8ec8-346436bdfde8.jpg)

Harald

**Comment by happycncer** [comment]
Duh, I just knew it'd be something simple! (a bit like me?)

Many thanks Harald, appreciated....
happycncer
