### ISSUE TITLE
TimeSpan owerflowed error with 1.5.9, but ok with 1.5.1 

### ISSUE THREAD

**Issue by robomechs** [martin2250/OpenCNCPilot#139]
![image](https://user-images.githubusercontent.com/8062959/88330278-d8a5eb80-cd33-11ea-8438-a32fd4201f30.png)
win10 1.5.9

**Comment by robomechs** [comment]
G90 G91.1 G21 G17
G01 X0.0 Y0.0 Z0.0 F500
G01 Z10.0
G01 X20.0
G01 Y20.0
G01 X0.0
G01 Y0.0
G01 X-10.0 Y-10.0

**Comment by robomechs** [comment]
up to 1.5.3 is ok
1.5.4, 15.5 - error

**Comment by martin2250** [comment]
Hi Yaroslav,

I've found the error, you used a feed move (G1 instead of G0) before an absolute position was established. This should not produce the error seen. I'll fix it soon, until then just use "G0 X0 Y0 Z0" at the beginning of the file for the time being.

Cheers,
Martin

**Comment by robomechs** [comment]
Thank you!
