### ISSUE TITLE
Extend size of probing mesh by user set amount in all directions

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#141]
Hi Martin,

on my last projects I had the problem that I had to extend the probing mesh beyond the borders you derive from the gcode.
Concretely, I wanted to carve a thin line at the border of my workpiece, where no gcode was created for.

To accomplish this, I had to modify all four coordinates manually in the correct direction. Feasible but dull and error-prone.

To get out of this, a checkbox "Extend borders" and a related edit control "amount" would be fine.

Harald

**Comment by martin2250** [comment]
Hi Harald,

thanks for the idea!

Martin

**Comment by deHarro** [comment]
Hi Martin,
you're welcome :)
Harald
