### ISSUE TITLE
No EXE available... intentionally?

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#142]
Hi Martin,

do you plan to publish the EXE for version 1.5.10, too?

Another question:
How can I get to the releases section of your github from the main page of OCP? I didn't find a link or button... but I'm sure I did find it in the past.
Thanks!

Harald

**Comment by martin2250** [comment]
Hi Harald,

thanks for pointing this out!! I had the zip file, just forgot to actually upload it :sweat_smile: 

![image](https://user-images.githubusercontent.com/8293473/89647437-dc9e4580-d8bd-11ea-8653-9b488c5edf9d.png)

I'm still not sure wehter or not to like Github's new design...

Cheers!
Martin

**Comment by deHarro** [comment]
Ah, see it! Thanks!
