### ISSUE TITLE
"Apply HeightMap" should be possible only once -> Graying

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#143]
Hi Martin,

I remember, that this topic was raised in the past by another fellow, but I didn't find it.
Perhaps it's part of one of the lengthy discussion threads and got missed...

Please implement graying the "Apply HeightMap" button when it is issued to the current file.

One can work around for sure by reloading the file and then be attentive to one's own clicking around, but being guided by OCP would be fine, anyhow :-)

Harald

**Comment by martin2250** [comment]
Hi Harald,

sorry, the email got buried. I'll work that into the next update!

Martin

**Comment by martin2250** [comment]
Hi Harald,

I added a warning in 1125b642db618bd4ca441eabe7ceb4fa45e59187.

Grüße,
Martin
