### ISSUE TITLE
OpenCNCPilot on Marlin

### ISSUE THREAD

**Issue by Diego1983938** [martin2250/OpenCNCPilot#144]
I have a MPCNC. 
I have dual endstop for autosquare. 
The board is a ramps 1.4
The firmware is Marlin.
I wonder if OPENCNCPILOT can run in marilin or just is for GRLB firmware...

Thanks...

**Comment by martin2250** [comment]
Hi Diego,

OpenCNCPilot only supports grbl. You should be able to compile grbl for yourself to run on the ramps 1.4 board. You'll lose autosquare, but I've used a dual-Y setup without autosquare for years, so that's not a dealbreaker.

Cheers!
