### ISSUE TITLE
Using Gcode from Flatcam

### ISSUE THREAD

**Issue by slorole** [martin2250/OpenCNCPilot#145]
For starter's I love this program.
It works great with gcode coming from pcb-gcode.  But coming from Flatcam its another story.
when you first load the gcode it has a long list of errors. maybe it just don't support files coming
from flatcam.
I have only found one other person with this issue and he had no answer.
I attached a .png so maybe you can see my issue.
But it's still a great program.  Thank You
![opencncpilot warnings](https://user-images.githubusercontent.com/71222383/93943606-8021a900-fcf8-11ea-9e1e-5268656bce68.jpg)

**Comment by martin2250** [comment]
Hi @slorole 

you can safely ignore all these warnings. I should probably get rid of these 'zero legnth' warnings.

The second warning is a bit more interesting, it means that the gcode uses G1, without setting the feed rate (Fxxx) first. You should try to find out why, but the code will probably still run fine.

Cheers!

**Comment by slorole** [comment]
Well it seems to work just fine after some adjustments in Flatcam. 
I think it looks good on my scrap piece's anyway.
                              thank you for your Time and Work
![IMG_20200925_092122094](https://user-images.githubusercontent.com/71222383/94280823-7e7ffd00-ff13-11ea-9f13-f6e081bee91a.png)

**Comment by martin2250** [comment]
the bottom PCB looks pretty clean!
