### ISSUE TITLE
Retraction Height when Probing

### ISSUE THREAD

**Issue by happycncer** [martin2250/OpenCNCPilot#147]
OK Guys, worked it out now. Have to say language used is not that intuitive, I think this particular title would be better named as 'Retraction Height' rather than 'Minimum Height'. Never even thought of altering this one to get done what I wanted to do.

Have now increased this to 1.5mm and all is good in my garden!
![OPC Retraction2](https://user-images.githubusercontent.com/35902417/97708123-30c95800-1ab0-11eb-80f6-20661a29ac31.JPG)

Thanks to all, willow52

_Originally posted by @happycncer in https://github.com/martin2250/OpenCNCPilot/issues/28#issuecomment-719539900_

**Comment by deHarro** [comment]
Hi Martin!

On changing texts...
How's about implementing a translation option?
I'm sure here are some guys that will help in translating to their native language.

And I myself may perhaps understand the one or other topic better afterwards (when OCP speaks german to me)... ;-)

Harald

**Comment by martin2250** [comment]
Hi Harald,

I wouldn't oppose adding translations to OCP, but that would require quite a bit of effort. (At least I think so, never used the internationalization features of C#/WPF). If there is anyone willing to invest the time, I'll gladly merge the pull request :)

Martin

**Comment by deHarro** [comment]
Hi Martin,

time would be no problem for me, but I tried to implement a second COM interface into your code some time ago and failed piteously.
So I have to admit, I'm not speaking C#, and I feel too old to try to get acquainted with it :)

Harald

**Comment by martin2250** [comment]
Hi all,

I added some better explanations in 2a23fb2dcf19f6da9bc781af9301655d5c57f9d9.

Cheers!
