### ISSUE TITLE
Compiled Zip file for release 1.5.11 runs as 1.5.10 

### ISSUE THREAD

**Issue by Win-doze** [martin2250/OpenCNCPilot#154]
Hi,
I downloaded he compiled zip for 1.5.11 and after expanding the folder and running the file received the screen prompt that a new update was available. The link took me to the file location for the one I was running! The about tab in the program indicated I was running 1.5.10.

I am not sure if the compiled zip is 1.5.10 or 1.5.11.

thanks

Andy

**Comment by martin2250** [comment]
Hi Andy,

you're absolutely right, I uploaded the old version on accident. It's fixed now.

Thanks,
Martin
