### ISSUE TITLE
Opencncpilot on winxp

### ISSUE THREAD

**Issue by PinoS56** [martin2250/OpenCNCPilot#155]
Hi Martin,
Hello everybody,
the program is great for me making pcbs with my cnc, i use it with my laptop with win 8.1,
however I would like to be able to use it on the desktop PC of my laboratory which has win xp 32 bit operating system and which I do not want to replace because I find it less cumbersome to use.
Is there a possibility to release a version compatible with win xp 32 bit ...?
It would be a welcome feature to many users.
Sorry my bad english, it's from google translate
Best regards...

**Comment by martin2250** [comment]
Hi, sorry for the slow response. Currently, I don't have a PC to test this or the time to implement it. If you know a bit about C# / Visual Studio, you can try to change some of the project properties to (maybe) make it work. If everything still works as normal afterwards, I can copy these changes to the official version of OCP.
Cheers!
