### ISSUE TITLE
bdring port crash

### ISSUE THREAD

**Issue by jschoch** [martin2250/OpenCNCPilot#156]
![image](https://user-images.githubusercontent.com/20271/111171972-a6672980-8562-11eb-8633-8952a843c537.png)

**Comment by jschoch** [comment]
![image](https://user-images.githubusercontent.com/20271/111172311-f219d300-8562-11eb-913a-2a743db0e16c.png)

**Comment by martin2250** [comment]
What version of grbl are you using? Looks like five axes are reported instead of three. There is a setting somewhere to ignore additional axes, that should make it work.

**Comment by jschoch** [comment]
this is resolved with the ignore additional axis option.
