### ISSUE TITLE
Z axis movement slow when board used Imperial units

### ISSUE THREAD

**Issue by pswarman** [martin2250/OpenCNCPilot#17]
I haven't collected any evidence for this; but I original design my Eagle board layout using Imperial units. I ran it through GCODE then CNCPilot. The Autolevelling worked and I then used the modified .tap file with grblControl to etch the pcb. There was some positioning of the drill head, it started and then when responding to moving the tool to the board the movement was incredibly slow (like go to bed and come back the next day for one instruction!). This is just a guess but it seems you convert the .tap file measurements in Inches to mm and somehow don't convert the Z axis movement. Apologies if this is me screwing it up. When I go back to Eagle and use cm (mm) everything works fine. 
I should add that when the probing is being done there are about a dozen errors thrown out on the screen for each sample point. These don't seem to affect the end result.

**Comment by pswarman** [comment]
![img_20170320_0002](https://cloud.githubusercontent.com/assets/10095050/24126994/41e381bc-0dc9-11e7-90e1-eb482f4c0c17.jpg)
I've just found a before and after .tap file print I did when I was trying to understand what had happened. The 2 files where imported into Excel and shown side by side....there are a few of my scribblings to interpret the GCodes. I hope this helps....... See the original tap is in inches and your program converts it to mm. Cheers . Paul

**Comment by martin2250** [comment]
Hi Paul,

fixing the feedrates was just a matter of two lines, I simply forgot to convert them to metric as well.
I don't think this was specific to the Z-axis, but Z was simply the first (non-G0) command affected by the feedrate.
I'll probably make a new release soon-ish with this fix included.

> I should add that when the probing is being done there are about a dozen errors thrown out on the screen for each sample point.

Can you post a screenshot of these error messages? which version of OpenCNCPilot and grbl are you using?

Greetings, Martin

**Comment by pswarman** [comment]
grblControl is verion 0.8
GRBL is 0.9j according to the supplier (I do not know how to check this?)
OpenCNCPilot is the latest version (I can't actually see a version number on the program window).

These errors come when I connect to the machine:
![image](https://cloud.githubusercontent.com/assets/10095050/24144101/e957a018-0e23-11e7-93ba-771422c1ebba.png).

I'll send the other probe errors shortly....hopefully!

**Comment by pswarman** [comment]
Here are a few of the error messages for one probe...
![image](https://cloud.githubusercontent.com/assets/10095050/24144689/135b8fb2-0e26-11e7-91d5-6bdc89c1fab6.png)
I set the option to ignore errors....not sure if that is significant.

**Comment by pswarman** [comment]
![image](https://cloud.githubusercontent.com/assets/10095050/24144799/827e788c-0e26-11e7-9a55-ed90ecdf4ad6.png)

**Comment by martin2250** [comment]
You'll have to upgrade to GRBL v1.1f or use OpenCNCPilot v1.1. The later versions don't support grbl 0.9
