### ISSUE TITLE
New man on the blok :)

### ISSUE THREAD

**Issue by Plovmann** [martin2250/OpenCNCPilot#170]
Hallo All.  
Im a new user of OpencncPilot, and I find it great.  I dont even know  about such program :)   Im normerly just du in wood on my CNC. 

My name is Lars, Im from Denmark

**Comment by martin2250** [comment]
Hi Lars, thanks for introducing yourself. Good to have you here!

I'm moving this to discussions, so it can stay open.

Cheers!
