### ISSUE TITLE
Probbing Feed Rate setting

### ISSUE THREAD

**Issue by thekannex** [martin2250/OpenCNCPilot#179]
Hi there, first i have to say this program is awesome, thanks a lot. My issue is I am using small motor on my cnc and vref amps are so little with this condition when i start probbing steppers are shaking not moving, I can increase vref but steppers are getting so hot. I think İf I  can set the probbing feed rate there is no issue. Sorry for my bad english. Thanks for your interrest.

**Comment by martin2250** [comment]
Hi, what exactly are you asking? You can change the probing feedrate in the settings menu, but it should already be fairly slow.

**Comment by thekannex** [comment]
Thank you for fast reply! I find out after you reply.
