### ISSUE TITLE
cannot get arrow keys to work or run to darken from grey on probing

### ISSUE THREAD

**Issue by cwbeson** [martin2250/OpenCNCPilot#182]
Hi there and thanks for using OpenCNCPilot,

before you submit this issue please make sure to check the following things:
- you're using the latest version of grbl (1.1f)
- you have the most recent version of the [.NET Framework](https://www.microsoft.com/net/download/dotnet-framework-runtime) (minimum 4.7)

If you still need help, delete this text and describe your problem and I or another member of our small community will help you.

**Comment by martin2250** [comment]
We cannot help you with the little info you provided. Can you explain your problem better?
