### ISSUE TITLE
engine speed

### ISSUE THREAD

**Issue by ghost** [martin2250/OpenCNCPilot#187]
.

**Comment by ghost** [comment]
Greetings to everyone. I'm new to the CNC hobby. I have a question. What should be the engine speed when making PCB with a 0.1mm engraving tip? Speed ​​120mm/min. Is there a standard for this?
How do you calculate?

**Comment by martin2250** [comment]
Hi Mehmet,

set your spindle rpm as high as it will go and then just test increasing feedrates until the result is no longer good. With 30k rpm at the spindle, I usually milled circuit boards at 400 mm/min.

Cheers
