### ISSUE TITLE
isolation job 

### ISSUE THREAD

**Issue by ghost** [martin2250/OpenCNCPilot#188]
Friends, scraping all the paths for insulation is very annoying and time consuming. I add a 0.1 mm thick path around the areas to be soldered. This way I save time. Does anyone have similar inventions other than solder mask?   :-)

![2](https://github.com/martin2250/OpenCNCPilot/assets/132232142/290bfdd4-2d02-49c4-80ca-9c73e72b1897)
![1](https://github.com/martin2250/OpenCNCPilot/assets/132232142/94f68e86-b636-4dad-9f0b-d13d66ad96e9)
![3](https://github.com/martin2250/OpenCNCPilot/assets/132232142/5c471ec1-88bb-4ea5-9acb-a2ee3557ca0a)

**Comment by martin2250** [comment]
not sure why the extra boxes around your pads end up in flatcam, maybe you imported an extra gerber layer? you should be fine with just the copper layer.

**Comment by mehmetcihanildiri** [comment]
> Pedlerinizin etrafındaki ekstra kutuların neden düz cam'e dönüştüğünden emin değilsiniz, belki de fazladan bir Gerber katmanı içe aktardınız? Sadece bakır tabaka ile iyi olmalısın.

![_20240504_133731](https://github.com/martin2250/OpenCNCPilot/assets/132232142/adf4d331-facb-46e2-9b68-71bb1c850a63)

Thanks

**Comment by ghost** [comment]
I don't want to dig around the roads. Processing time is getting longer.

![_20240504_133731](https://github.com/martin2250/OpenCNCPilot/assets/132232142/cdce935f-2f2b-4119-956c-b1573a326e48)
