### ISSUE TITLE
wrong version number in GRBL 1.1f link

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#20]
perhaps not worth to mention, but perhaps you should correct the text for the link to "GRBL 1.1f" on the download page

![grafik](https://cloud.githubusercontent.com/assets/26298406/24205965/28d1daca-0f1d-11e7-9bb6-63020d575a29.png)

The link itself is fine, but I was starteled, when I read it for the first time, thought "wow, already a new version... what is wrong with 1.1f?"
Harald

**Comment by martin2250** [comment]
thanks!
