### ISSUE TITLE
question concerning the sources

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#21]
Hi Martin,
is it ok to raise issues for every little question?
Is there perhaps another way to contact you?

I recently (some days ago) downloaded the sources to get hold on your latest changes and found a file "test.pfx" as part of the solution, but not the file itself.
To get the solution to compile I had to remove the file from the solution.
What's about that file? Seems not to be urgently needed...

Harald

**Comment by martin2250** [comment]
Hi Harald,
I tried signing the executable to get rid of the 'do you trust this application' warning, it didn't work out too well. the file has already been removed since.

Martin

**Comment by deHarro** [comment]
But it is still part of the solution.
Perhaps you should remove it... but I surely can do that on my own ;-)
Harald

**Comment by martin2250** [comment]
nope, it's already removed: https://github.com/martin2250/OpenCNCPilot/commit/c130aef3da576261ad7e2429ea58aeed9bcd4d79#diff-972cfd1654e677bad6a6a6bd953a09b5

**Comment by deHarro** [comment]
Mhmm, when I open the solution of the ZIPed project, downloaded via button "Clone or Download" on the Code page and open this via double click on the sln file I get this:

![grafik](https://cloud.githubusercontent.com/assets/26298406/24215903/939dfd94-0f3a-11e7-8442-7a290bfccfe2.png)

In the csproj file in the ZIP archive you'll find 

![grafik](https://cloud.githubusercontent.com/assets/26298406/24216014/f548d7a8-0f3a-11e7-8f83-027bb2f65b57.png)

and 

![grafik](https://cloud.githubusercontent.com/assets/26298406/24216040/0a1aaf6c-0f3b-11e7-8552-9088775e9b9f.png)

respectively.

I downloaded this version at 16:49 today, perhaps it's too old?
Do you know how github handles those ZIP archives?
I thought, they are packed just in time, but that doesn't seem to be true.
The actual sources contain no ".pfx"... (??)

**Comment by martin2250** [comment]
I just downloaded the zip file and I can't find any reference to test.pfx in the .csproj file

**Comment by deHarro** [comment]
Upps, my fault, sorry!
I just realized, I used the ZIP from the releases page for my screen dumps.

I was distracted by the naming  of the ZIP "OpenCNCPilot-1.3.1.zip" which fits to the version in the AboutBox.

Is then there an older .csproj file? Or perhaps now updated as well?
Leave it alone - my fault :-(
