### ISSUE TITLE
Tooltip of buffer progress bar wrong?

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#22]
Tooltip of the progress bar says, Bit 1 of $10 has to be set.
On my setup I have $10=0 and the progress bar works like a charm.
Perhaps a remainder from implemntation for GRBL 0.9xx?

Harald

**Comment by martin2250** [comment]
No, it's a new feature from grbl 1.1: If bit 1 of $10 is set, grbl will report the remaining space in it's receive buffer which can be used to 'sync' the buffer when there was an error (click on the progress bar to sync).

**Comment by deHarro** [comment]
Ah, ok, thanks!
