### ISSUE TITLE
Question on program structure

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#23]
Hi Martin,
I already talked about my idea to attach a joystick to a second serial to issue jog commmands.

Can you please give me a clue where to start when trying the implementation on my own?
I added another tab in the settings dialog for the parameters of this second serial, but I'm unable to find e.g. the routine reacting on changing the COM port. No "on change" or similar.

I know, perhaps a too difficult task to kickstart someone into foreign code...
Harald

**Comment by martin2250** [comment]
Hi Harald,
All the Settings are done with Bindings, so changing the text will automatically change the Value in 'Settings.settings'.
As for where to implement this: probably either Machine.cs (=> Worker Thread) or in a new MainWindow.cs file, like Probing.
Ask away if you have any more questions!
Martin

**Comment by deHarro** [comment]
Hi Martin,
"Ask!" sounds promising, thanks! :-) but I may have to dive into C# prior to asking "silly questions".
I'll keep you posted...
Harald
