### ISSUE TITLE
Return to zero.

### ISSUE THREAD

**Issue by bocum4** [martin2250/OpenCNCPilot#24]
Hi there,

I've noticed that, when the program finishes doing a tool pass it does not return to Zero and when I click the "return to zero" option, it only returns virtually but not mechanically, that is, it only returns in the software but not in my CNC. What am I missing? Is there any way to do this?

Cheers!

**Comment by luizabbadia** [comment]
Hi, I use to edit the gcode and put G00 X0 Y0 right before M05 M02 presented at the end.
I know it´s not perfect but does the job.

**Comment by bocum4** [comment]
Ahh yeah... didn't realised I could edit the coordinate lines/instructions. I'll try that asap.

**Comment by martin2250** [comment]
Hi,

there is no 'return to zero' button, only 'set zero'. You can either edit the file (thanks @luizabbadia ), use jogging/manual commands or create a macro for that.
