### ISSUE TITLE
G2 G3 supports

### ISSUE THREAD

**Issue by pedro06** [martin2250/OpenCNCPilot#25]
Does a query support G2 and G3?

**Comment by martin2250** [comment]
what exactly do you mean by 'a query' ?

**Comment by pedro06** [comment]
I want to know if the program supports the G-Code G2 and G3.

**Comment by martin2250** [comment]
Yes, it does. It also supports splitting up large arcs into smaller sections to improve surface contact.

**Comment by pedro06** [comment]
Martin, thank you very much for your program.

**Comment by martin2250** [comment]
sure thing, glad you like it :)
