### ISSUE TITLE
vector proccessing feature

### ISSUE THREAD

**Issue by mkeyno** [martin2250/OpenCNCPilot#27]
sorry to open ticket for my question , actually I look for GUI interface for my GRBL board , I've find couple of good repo's for that matter however some of the only visualize and send gcode file to serial port and others only convert vector file to gcode, I was wondering if you have any plan to combine such feature in your repo and probably look at some [other repo](https://github.com/arkypita/LaserGRBL/issues/29) with missing feature 
BR

**Comment by martin2250** [comment]
Hi,
I won't add such a feature, that's the job of whatever CAD/CAM software you're using.
You can take a look at bytemaster-0xff's [fork](https://github.com/bytemaster-0xff/OpenCNCPilot), he plans to add (or already has) an importing feature for eagle .brd files.

Martin
