### ISSUE TITLE
OpenCNCPilot serial connecting error

### ISSUE THREAD

**Issue by ronori** [martin2250/OpenCNCPilot#29]
![error1](https://cloud.githubusercontent.com/assets/28160053/25889806/6d244e82-356b-11e7-85c5-d115750ddd78.jpg)
![error2](https://cloud.githubusercontent.com/assets/28160053/25889805/6d1a21a0-356b-11e7-985a-df599d06f145.jpg)

Hi Martin,
I wanted to thank you for the beautiful project you made.
I already used your first version of the autoleveler program with GRBL.
I am writing to you because I have problems connecting to the OpenCNCPilot program.
When I select the serial port where I obviously have GRBL version 1.1f, the program returns the following error:
I tried connecting to other programs on the same serial port, for example universal gcode sender connects without any problems.
You could help me understand why OpenCNCPilot does not connect to the serial port.

**Comment by martin2250** [comment]
Hi Romano,
you forgot to add the pictures.
Also can you please answert the questions from my email?

**Comment by ronori** [comment]
Hi Martin,
yes i'm sorry , now i have update issue with picture.
and i installed latest release of OpenCNCPilot 1_3_1

**Comment by martin2250** [comment]
When did you start having this issue?

**Comment by ronori** [comment]
OpenCNCPilot never worked.
I also tried on different computers but the problem is the same.
I try to connect with UniversalGcodeSender and GRBL connects.
While OpenCncPilot tells me the error in the screenshot I've attached

**Comment by martin2250** [comment]
Just a wild shot, but can you try running it on an english or german version of windows (possibly windows 10)? maybe in a virtual machine

**Comment by willyreta** [comment]
tengo el mismo problema, en windows 7 me funciona perfecto, cuando quize ejecutarlo en windows 8.1 me dio ese error al querer conectarme, he probrado ejecutandolo como administrador y no funciona...

**Comment by willyreta** [comment]
solucion: instalar net framework 4.6...

**Comment by ronori** [comment]
Installing .Net 4.6 also fixes my problem.
Thanks so much
