### ISSUE TITLE
Save Modified Gcode

### ISSUE THREAD

**Issue by GeerGuy** [martin2250/OpenCNCPilot#3]
Is there a way to save the new gcode after the height map has been applied?

I would like to use other applications for the actual sending.

Thanks

**Comment by martin2250** [comment]
Currently not, I'll put it on my todo list

**Comment by martin2250** [comment]
addressed in release v1.2. thanks for the suggestion !

**Comment by GeerGuy** [comment]
Is GRBL 1.1 required, or will 0.9 work as well?

Thanks

**Comment by martin2250** [comment]
> Updates include:
> -support for GRBL 1.1f (**no backwards compatibilty**)
> -ability to save modified files (#3)
> -file dialogs remember their location (#11)

**Comment by GeerGuy** [comment]
OK, my Shapeoko 3 officially only uses 0.9, so I will have to wait to try it,  Thanks
