### ISSUE TITLE
OpenCNCPilot 

### ISSUE THREAD

**Issue by Benjamincreator** [martin2250/OpenCNCPilot#31]
Hey Martin 

How hard would it be to make a version of the Open CNC Pilot for Mac OS X? because lots of people use Mac for use with CNC machines etc?

Cheers Benjamin

**Comment by martin2250** [comment]
Hi Benjamin,

pretty hard, I've never used a Mac and I don't have access to one for testing.
You could try Wine (Mono doesn't support WPF IIRC), but I think setting up a VM would be much easier and more stable.

Greetings
Martin
