### ISSUE TITLE
Feedrate of 100 gets deleted when simplified

### ISSUE THREAD

**Issue by canbaytok** [martin2250/OpenCNCPilot#35]
Just noticed this bug and I thought I might let you know. When you open up a gcode file with the feedrate set to 100 and simplify the file the feedrate setting gets deleted and grbl defaults to a very slow feedrate, which forces you to pause the job, enter the feedrate through the manual control box, and continue the job. I just tested it with a feedrate set to 101 and it does not get deleted by the simplifier. 

![image](https://user-images.githubusercontent.com/25607877/34449761-63a1634c-ecfc-11e7-904a-95e5483413d3.png)
![image](https://user-images.githubusercontent.com/25607877/34449765-6e3aff98-ecfc-11e7-9c33-eade3b37a857.png)

**Comment by martin2250** [comment]
Thanks for pointing this out!
The problem was that the default feed rate was set to 100mm/min, so it wouldn't detect a change in feedrate. This also meant that a feed rate of 100mm/min was assumed when no feed was specified (which does not comply with the gcode standard)
