### ISSUE TITLE
OpenCNCPilot Icon

### ISSUE THREAD

**Issue by martin2250** [martin2250/OpenCNCPilot#39]
Hi everybody,

I want to add an icon to OpenCNCPilot but I have no good ideas nor the artistic talent to draw one. If anybody has a good suggestion or wants to send one in, please do so :)
(svg file preferred)

Cheers!
Martin

**Comment by deHarro** [comment]
are you able to make a mini version of your demo warped board?
...
Ok, a JPG version at least:
64x64 pixels:
![2018-01-08_223749_resize 2](https://user-images.githubusercontent.com/26298406/34693892-850195a4-f4c5-11e7-8a08-f6e567b84bf9.jpg)
32x32: 
![2018-01-08_223749_resize](https://user-images.githubusercontent.com/26298406/34693958-b78f642e-f4c5-11e7-8e01-95ea08675bbd.jpg)
Mhmm, not very impressive :(

Harald

**Comment by S2000Stefan** [comment]
Hi Martin,
here my first design.
![ocncpb](https://user-images.githubusercontent.com/35189051/34742522-555ef166-f57e-11e7-90f8-c0779a9a6ccf.png)
128x128 Pixels
Stefan

**Comment by Miq1** [comment]
I fumbled another one :-)

![cnc-pilot64](https://user-images.githubusercontent.com/25884124/34783758-b08aa3c4-f62c-11e7-8ac4-5e4d48264d45.png)
[Temp.zip](https://github.com/martin2250/OpenCNCPilot/files/1619656/Temp.zip)

The ZIP contains the SVG source, a windows ICO file and the 64 pixel example.

The pilot clipart was taken from the Open Clipart Library and is free to use.

**Comment by martin2250** [comment]
Hi everyone!

Thanks for your suggestions, I really like both of your suggestions. I kinda prefer the the colorful background of Michaels icon though I'm not too sold on the actual pilot clipart. The industrial look of Stefan's icon is also great, but it doesn't really stand out placed on my Desktop.
I just quickly put another clipart on Michaels background:
![cnc-pilot svg](https://user-images.githubusercontent.com/8293473/34793351-64c689ac-f64b-11e7-8c45-3f9631848937.png)
![cnc-pilot-1 svg](https://user-images.githubusercontent.com/8293473/34793352-64e81586-f64b-11e7-8f39-383d0f3addfb.png)

What does everyone else think of these four (I think you'll forgive me for not including yours Harald)?

Martin

**Comment by Miq1** [comment]
If I was to choose one with the aircraft, I'd take the second. The first has the plane a bit distorted.

I could offer another, if you like:
![cnc-pilot64_2](https://user-images.githubusercontent.com/25884124/34822204-626ec4d2-f6c6-11e7-8f8c-c48e6a24ffb2.png)
[Temp.zip](https://github.com/martin2250/OpenCNCPilot/files/1622251/Temp.zip)

**Comment by martin2250** [comment]
Yeah, that last one looks really great! I'd just change the gradient and scale a bit when I find some time

**Comment by deHarro** [comment]
Hi Martin, 
nix da, ich bin jetzt total eingeschnappt ;-)
Yes, this last one is the best out of all proposals, I think, too.
Harald

**Comment by martin2250** [comment]
Okay, I think I found a design that I like:
![opencncpilot-icon](https://user-images.githubusercontent.com/8293473/35471831-8ae732a6-0363-11e8-98dc-44e1ae2c3d32.png)
everything smaller or with less contrast is pretty much invisible with my desktop icon size.
Try it out on your desktop and let me know what you think!

Greetings everyone!

**Comment by Miq1** [comment]
Nice! ;)

**Comment by S2000Stefan** [comment]
If already such a motley icon I personally like the suggestion of Miq1 better, 
sorry Martin.  ;)
Stefan

**Comment by deHarro** [comment]
Hi Martin,

just added your icon to the desktop link of OpenCNCPilot...
The Icon looks awful on my 1600x1200 monitor:

![grafik](https://user-images.githubusercontent.com/26298406/36482354-543f2268-1713-11e8-99bb-83b58b5e7902.png)

I used Paint.net to change the PNG to ICO format and selected the resulting ICO as source for the icon picture.
Perhaps you got better results? If so, please let us participate :-)
Thanks!
Harald

**Comment by deHarro** [comment]
It seems like you have to add dithering to your characters, so the slanted lines and curves are approximated by shades of black to gray (or whatever color is adjacent).

I hoped that would be acomplished by the conversion process within Paint.net, but obviously it is not.
Perhaps there are better icon converters around but I don't want to use an online tool for that (at least on an image beeing not my property).
Harald

**Comment by Miq1** [comment]
You may try IrfanView - worked fine for me.

**Comment by deHarro** [comment]
I just found another great program for converting png to ico fomat: [dihav PNG2ICO](http://www.dihav.com/view.php?id=png2icon)

The result is fine:

![grafik](https://user-images.githubusercontent.com/26298406/36484002-23e7bd82-1718-11e8-8b50-333741b34140.png)
