### ISSUE TITLE
Generating probe area with negative values does not work

### ISSUE THREAD

**Issue by canbaytok** [martin2250/OpenCNCPilot#40]
I think I've found a bug while trying to generate a probe area.

Somehow the area does not take the first component of the X axis into consideration, unless you press the "Size from GCode" button. I tried it with both positive and negative values.

![image](https://user-images.githubusercontent.com/25607877/34882248-3f23cd42-f7b6-11e7-9a85-ca58fabcf0dc.png)
This is the initial probe are.

![image](https://user-images.githubusercontent.com/25607877/34882266-514bf97c-f7b6-11e7-80c2-e63da1e3f47b.png)
This is the probe area with the first component of the X axis set to `20`. Notice that the probe area is still the same.

![image](https://user-images.githubusercontent.com/25607877/34882317-85f995c6-f7b6-11e7-8b08-6c842aebcedb.png)
Same with first X point set to  `-20`

![image](https://user-images.githubusercontent.com/25607877/34882372-b12ac616-f7b6-11e7-8241-d2309279e612.png)
"Size From GCode" somehow works

Best Regards

**Comment by canbaytok** [comment]
Ok nevermind that. I just checked out the latest commit (https://github.com/martin2250/OpenCNCPilot/commit/92c63c5d3ddaedd278c2d1b3eb16c42c126c1eef) and it seems to fixed there.

Thanks alot Martin!

**Comment by martin2250** [comment]
Hi, was this an issue that came with the recent releases and does it work in the latest release or only in the current code on github? Thanks for bringing this to my attention, I might have to create the next release sooner than planned.

Good to see you're still around!

**Comment by canbaytok** [comment]
The bug is present in the latest release and fixed in the github code. I check again later and report back.
