### ISSUE TITLE
GrblSettingsWindow (II)

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#45]
Hi Martin!
When editing parameters in GRBL settings, you are able to step through the edit controls by entering \<TAB\>.
If you do so and change some parameters before applying, then the changes are visualized in the fading display zone, stating the transmission to GRBL.
Try that, close and reopen the dialog -> not all values are transmitted to GRBL.
Even worse: I didn't change the $10 parameter, left it on "0", but this param changed to "60".

Changing and applying the paramters one at a time, sending the changed param to GRBL after every edit operation works fine.

Do you run into race conditions when sending the changed params consecutively too fast?
Have in mind that saving something to EEPROM takes some time.
Do you wait for "ok" after sending a parameter or react on "stop" (or whatever GRBL issues when it has hickup)?

Harald

**Comment by martin2250** [comment]
Hi Harald,

thanks for the feedback! I'll look into it asap (hopefully tomorrow).
Sorry if it's caused any damage.

Martin

**Comment by deHarro** [comment]
Hi MArtin,

no, no damage, I just played araound with the new version at my office PC, no real hardware there :)
Harald

**Comment by martin2250** [comment]
Hi Harald,

can you try to reproduce this behavior with the latest commit? (esp. the $10 thing) Do you have VisualStudio installed or should I send you a binary?

Greetings

**Comment by deHarro** [comment]
Hi Martin,
first I tried to reproduce the error with V1.4.3.0 to verify, that your changes (supposing you changed something).
Clicking around frantically I got that peculiar error message:
![grafik](https://user-images.githubusercontent.com/26298406/35474799-7f7153f4-0393-11e8-9128-a79f7050e7bc.png)
I had 800 in "X-axis max rate" and changed the value by selecting the 8 and replaced it by 7, then hit apply.
You see, $110=700 is taken, but we get an error mesage, that $110=800 is not supported.
Info: the $10 thing I didn't encounter again so far.
Should I now update to the lates commit, or do you think I have to provide you with additional tests?
Harald

**Comment by deHarro** [comment]
H iMartin,
ok, I tortured your new settings dialog for some time now.
I think, the quirks I stumbeled over are gone. 
The version is 1.4.3.0, still, but I think you change that after finishing all edits.
Thanks for the annotations, by the way... ;-)

One last wish on this fabulous dialog:
Can you please get rid of this superflous area?
![grafik](https://user-images.githubusercontent.com/26298406/35475120-2210f93e-0399-11e8-8359-3c5c9a80d3de.png)
It makes me to use the full hight of my 1600 by 1200 monitor to display all parameters at once. Without this blank area a 1024er monitor will be sufficient, I think (the one at my mill).

Harald

**Comment by martin2250** [comment]
Hi Harald,

yeah, I'll increment the version number when I publish the next binary release.
I think the changes you suggested are really great!

Martin

**Comment by deHarro** [comment]
Thanks! :-)
I only fear sometimes that you think "oh no, Harald schon wieder..." ,-)
Harald
