### ISSUE TITLE
OpenCNCPilot with Raspberry?

### ISSUE THREAD

**Issue by Maude94** [martin2250/OpenCNCPilot#52]
Hi everyone,
I write because I would like to know if someone has tried to use OpenCNCPilot on a Raspberry and if that  is possible.
I would like to avoid to bring my laptop in the lab where there is a lot of dust and it is really a mess.
Let me know
Giorgio

**Comment by martin2250** [comment]
Hi Giorgio,

this isn't possible. As much as I hate it, WPF isn't supported on Mono, so you have to run OpenCNCPilot itself on a Windows machine.
You could
- cover your laptop (obviously)
- hide the laptop near the machine and use VNC to operate it (lower reliability, make sure to have a physical e-stop)
- use a windows SBC like the UP / UDOO
- use Chilipeppr / UGS platform (?) or Candle (not officially supported on ARM, probably doesn't work either)

Martin
