### ISSUE TITLE
Problem with probing

### ISSUE THREAD

**Issue by ghost** [martin2250/OpenCNCPilot#54]
hi all
i have a small problem with the probing. 
I can do the setup and make "create new" take size from the gcode. then i apply hightmap and start milling. 

but ... it just go down in to the pcb to deep ? in the start end of my pcb where i start probing it cuts the deepest cut in the pcb, and then it lift just a bit. ?? 
what im i doing wrong?

regards 
Pcb for fun

**Comment by martin2250** [comment]
Hi,

did you change anything between when you probed the PCB and when you milled it? (origin/tool/anything besides removing the cable).
is it too deep everywhere or only where you start probing?

Martin

**Comment by ghost** [comment]
hi 

no just open file>create new>size from gcode>apply hightMap>start. 
But stile off with the probing, and i can't find out why. it makes no sense at all.

any ideas ?

**Comment by martin2250** [comment]
did you close this on accident? besides this I don't know what could cause this. what engraving depth are you using? If nothing works and you're willing to try you can upload a video of your process to youtube/vimeo and attach a link here

**Comment by ghost** [comment]
accident. 
Im using flatcam to make the gcode, and cut 0.035 in depth. normlay i not have any problem with grbl and my cnc, only when i use OCP. 
i not have youtube or vimeo, but will look in to that.

**Comment by martin2250** [comment]
35 thou (0.9mm) seems wayyy too deep to me. I usually use around 0.1mm (0.004")

**Comment by ghost** [comment]
it is 0.0035 mm in depth. it works normaly for me in universal gcode sender. but not if the pcb i a bit bend

**Comment by martin2250** [comment]
Then I can't help you without a video, sorry

**Comment by ghost** [comment]
sure, working on it :)

![flatcam](https://user-images.githubusercontent.com/38467724/38976835-b8563180-43b2-11e8-9273-bee92e42854b.jpg)

**Comment by canbaytok** [comment]
I would suggest you triple check, whether or not FlatCAM is really in mm instead of inches and grbl is set to mm.
Make sure FlatCAM is set to mm in the application options and the project options.

As long as you probe out the zero Z point and dont G92 anything after probing, there shouldnt be problems.

**Comment by ghost** [comment]
it is, i can mil no problem witout OCP (but with the problem, not getting propper down all over the pcb)
Can't get the video to work. 
but i got this, i can do the probing and all good, but it is like it is reversing it. see picture

![cnc_ocp](https://user-images.githubusercontent.com/38467724/38990183-8650f63a-43d9-11e8-8766-bd61d8de4212.jpg)


hope it makes sense

**Comment by ghost** [comment]
i can easy make/ a small area without problem, so the setting in flatcam and my cnc most be okay ? the size of the 2221 is 5mmx6mm

![img_2866](https://user-images.githubusercontent.com/38467724/38990437-89cc0a88-43da-11e8-9a46-e9fcb343fb26.JPG)

**Comment by martin2250** [comment]
what does the result with OCP look like?   what you can also do is enable logging in the settings window and post the logfile here

**Comment by martin2250** [comment]
Hi, did you do any further tests? If not I'll close this issue for now.
