### ISSUE TITLE
Save window size (QoL change)

### ISSUE THREAD

**Issue by canbaytok** [martin2250/OpenCNCPilot#55]
Hi Martin,

Would it be possible to add a feature to save the window size, so the window is always as big as it was before closing, cause the first thing I do is resize the window :D

Just a QoL change :)

**Comment by martin2250** [comment]
Hi

yeah, that should be doable. I'll implement it this weekend if I find time. Thanks for the suggestion!

Martin

**Comment by canbaytok** [comment]
Looking forward to it!

Thanks a lot!

**Comment by martin2250** [comment]
better don't close this until I remember to do it :sweat_smile:
