### ISSUE TITLE
Jogging problems

### ISSUE THREAD

**Issue by gdipaolo11111** [martin2250/OpenCNCPilot#57]
Hi first off all thaks for this sowtware!

the joggin feature is not working at all on muy computer, I see the error: Expected Command letter $J=G91F500Y10

Could you help me?

thanks

**Comment by martin2250** [comment]
What version of grbl are you using?

**Comment by gdipaolo11111** [comment]
thanks this fast reply

Im using Grbl 0.9j

**Comment by martin2250** [comment]
and what does the Readme say? Right under installation, above quick start guide...

**Comment by gdipaolo11111** [comment]
Make sure to use GRBL version 1.1f (later versions may work but are yet untested)

Thanks ajajja

**Comment by gdipaolo11111** [comment]
just update and reset all $ parameters and now is working thanks
