### ISSUE TITLE
VcarvePro Mach3 outputs line numbers

### ISSUE THREAD

**Issue by rickmcolorado** [martin2250/OpenCNCPilot#58]
I used VcarvePro to create my gcode that is used to drive my CNC running on Mach3.  When I create the gcode it always outputs the line number as an example N100.  OpenCNCPilot will not accept this command.  How do I get around this issue?

Thank you

**Comment by martin2250** [comment]
Hi Rick,

short term: use Notepad++ to replace all Nxxx with a blank string (enable regular expressions and replace "N[0-9]+" with "")
long term: keep this issue open, I'll fix this when I find the time.

Martin

**Comment by rickmcolorado** [comment]
Thank you so much.





Rick McCaskill
303-682-0440 




-----Original Message-----
