### ISSUE TITLE
Spindle Cannot be stopped

### ISSUE THREAD

**Issue by xaoo** [martin2250/OpenCNCPilot#59]
I cannot stop my spindle after I connect this tool to my CNC (cnc 2418).
The only way I can is to disconnect the usb + power.

I saw also that when the app si opened, my mouse moves down at every click :)

**Comment by martin2250** [comment]
Hi George,

how is your spindle wired to the controller? I guess you've already tried M3/M5. What software were you using before?

> I saw also that when the app si opened, my mouse moves down at every click :)
What?! That's nigh impossible, OpenCNCPilot doesn't use a single function that controls the mouse cursor in any way.

Martin

**Comment by xaoo** [comment]
Hi Martin,

What I did, I`ve re-uploaded the 1.1f firmware, although it was, and it worked perfectly.
Thank you for your fast reply.

**Comment by martin2250** [comment]
Great, I'll mark this as resolved :)
