### ISSUE TITLE
QoL change: Prompt user to save heightmap or just force save

### ISSUE THREAD

**Issue by canbaytok** [martin2250/OpenCNCPilot#61]
Hi there Martin!

I was working on a new little project and routed out the copper traces. After I applied the solder mask and cured it I wanted to route out the pads, but unfortunately my PC crashed and I lost the heightmap, which made the pad routing impossible...

Would it be possible to add a feature, that saves the heightmap after the probing is finished and saves it in the folder the loaded gcode file sits in, or even just asks the user to save the heightmap?

Best Regards
sirsenor

**Comment by martin2250** [comment]
Hi sirsenor,

good idea, I'll probably add this as an option in the future.

Martin

**Comment by martin2250** [comment]
didn't try it out yet, but I'll test it when I get home: c4dae20eeccad1e61310d776036460be26cc9015
