### ISSUE TITLE
4th axis support

### ISSUE THREAD

**Issue by robomechs** [martin2250/OpenCNCPilot#63]
I've added 4th axis for STM32F103 (usbcnc), and tested it for a long time.
Now it's work.
https://github.com/usbcnc/grbl/issues/51
Сan I expect to support the additional axis in the future in your software?
(without visualization of course)

**Comment by martin2250** [comment]
Hi, this is amazing work! 
As far as I see it, OpenCNCPilot doesn't need to modify any code that contains the 4th axis, so you can use it right now, only the preview won't work.
I can add an option to ignore A/B/C axis commands for the preview, that means that the file will only get sent exactly as it is.

**Comment by robomechs** [comment]
Ok, the program is really running.
But in 4 axis mode there is no visualization for three axes.
Error always runs.
![2018-07-17_19-09-06](https://user-images.githubusercontent.com/8062959/42831282-9b020aa2-89f6-11e8-96cc-63e1380e36db.png)
![2018-07-17_19-09-50](https://user-images.githubusercontent.com/8062959/42831291-a0ab7b0a-89f6-11e8-820f-69dc0fa9ec56.png)
![2018-07-17_19-18-40](https://user-images.githubusercontent.com/8062959/42831305-a8da969e-89f6-11e8-87ba-57ef03e6f38b.png)

**Comment by robomechs** [comment]
Running messages with status "Received Bad Status" make the work unbearable.
Can't close issue.

**Comment by martin2250** [comment]
I can add this as an option when I have some spare time, for now you could modify the source code and quickly compile a custom version.
The relevant lines are [here](https://github.com/martin2250/OpenCNCPilot/blob/master/OpenCNCPilot/Communication/Machine.cs#L947) and [here](https://github.com/martin2250/OpenCNCPilot/blob/master/OpenCNCPilot/Communication/Machine.cs#L1030), you'd only need to cut the string m.Groups[2].Value before the third comma.
You can compile the project wihtout VisualStudio, there is a good answer on stackoverflow on how to do it.

**Comment by klembaris** [comment]
Hi, here you can look for 4 axis control software 
https://www.rcgroups.com/forums/showthread.php?2915801-4-Axis-Hot-Wire-CNC-%28Arduino-Ramps1-4%29-Complete-Solution

I just modified to A axis, for testing 4 axis should be ok.

[stm32F1034axis Grbl HotWire Controller.zip](https://github.com/martin2250/OpenCNCPilot/files/2238192/stm32F1034axis.Grbl.HotWire.Controller.zip)

**Comment by martin2250** [comment]
I created the fix in a separate branch: https://github.com/martin2250/OpenCNCPilot/tree/fourthaxis
Please try it out as I don't have a machine to test this on:
[OpenCNCPilot-4th-axis.zip](https://github.com/martin2250/OpenCNCPilot/files/2240824/OpenCNCPilot-4th-axis.zip)

**Comment by klembaris** [comment]
Hello. Still same errors in 4 axis mode.

![err1](https://user-images.githubusercontent.com/17252320/43408506-3b30b392-942a-11e8-978e-9d00040b791e.png)

Thanks.

**Comment by klembaris** [comment]
Hello,
works!

![errrok](https://user-images.githubusercontent.com/17252320/43413703-7166cf3c-9439-11e8-8b09-49636315d9b1.png)
 Thanks.
PS. Do not forget to check box in settings!

**Comment by martin2250** [comment]
Hi,

great! I'll test if it interferes with normal 3-axis operation, then I'll merge it with the master branch and it will be included in the normal version of OCP.

**Comment by klembaris** [comment]
Hi,
very nice!.

**Comment by yaroslavVl** [comment]
hmm. Nothing changed.
![2018-07-31_12-31-54](https://user-images.githubusercontent.com/8062959/43451699-359528ac-94be-11e8-89c2-816d48efe58e.png)

**Comment by robomechs** [comment]
GREAT!
Thanks.
![2018-07-31_12-55-56](https://user-images.githubusercontent.com/8062959/43452859-2cce52ea-94c1-11e8-9d50-a848698d93fe.png)

**Comment by robomechs** [comment]
![2018-07-31_12-57-46](https://user-images.githubusercontent.com/8062959/43452952-684382fa-94c1-11e8-8e8f-67e591663d20.png)

**Comment by yaroslavVl** [comment]
`Do not forget to check box in settings!`

**Comment by robomechs** [comment]
@klembaris right! **Do not forget to check box in settings!**

**Comment by martin2250** [comment]
right, I forgot the probe parser. I'll fix this before I merge with the master branch. Thanks!

**Comment by robomechs** [comment]
ok. it's work fine with 5 axis too)))

**Comment by martin2250** [comment]
Did you post any videos of your machine online? I'd love to see your 5-axis setup :)

**Comment by robomechs** [comment]
@martin2250 unfortunately I have only 6 axis test bench and 4 axis machine.

**Comment by martin2250** [comment]
please don't close this issue, this feature isn't fully implemented yet

**Comment by klembaris** [comment]
Hi Martin2250,

It is very complicated to make visualization like, left side x1y1(XYaxis) and right side x2y2(AZaxis)? Thanks.

**Comment by martin2250** [comment]
Hi,
yeah, that would require a lot of changes to the communication and UI subsystems. Anyways, that's outside the scope of this program anyways. I mainly wrote OpenCNCPilot for making circuit boards and 'normal' machining.
You could, however, also change only some of the code so it has one single view and XY and AZ are drawn in two fixed planes (aka XY at 'regular Z'=0 and AZ at 'regular Z'=200) and connect the points with lines. That way you could even have a 3D preview of what you're cutting. Feel free to fork OpenCNCPilot, this should be relatively easy to implement.

**Comment by klembaris** [comment]
Thanks for info :)

**Comment by S2000Stefan** [comment]
Hi Martin,
can you please fix the issue for the "Received Bad Probe" 
I use a blue pill (stm32) with GRBL four axis control. Thanks yaroslavVI for your work. 
If I want to create a hight map for PCB comes the error Received Bad Probe and the machine stands after one probe.
And by the way, in the window New HeightMap and manual input you have to enter a point twice. The first time it is not accepted. Example  X: 100.5 - 50.5   =  X: 1005 - 50.5
Editing works.

Great Icon  :)

Stefan

**Comment by martin2250** [comment]
Hi Stefan,

wait, this isn't fixed? Can you use UGS and copy/paste a few lines of probe responses here? I added some logic to ignore additional axes in probe responses a while back, so I'm a bit surprised.
Can you open a short issue for the "New HeightMap" window? I don't know when I can work on OCP again, so I probably won't remember this by myself.
The icon isn't my work, all the praise goes to @A-J-Bauer :)

Cheers!
Martin

**Comment by S2000Stefan** [comment]
Hi Martin,
here are some screenshots:
![ocp programmstart](https://user-images.githubusercontent.com/35189051/48014429-f4fc9180-e126-11e8-90ab-b3a23e2328f5.png)
Startup of OCP
![probe fail ocp](https://user-images.githubusercontent.com/35189051/48014499-1a899b00-e127-11e8-8fb8-3f6683c09fe7.png)
Probe Fail making height map
![ugs start](https://user-images.githubusercontent.com/35189051/48014588-47d64900-e127-11e8-89a8-6d798f4abbad.png)
UGS Startup
![ugs probe](https://user-images.githubusercontent.com/35189051/48014619-56bcfb80-e127-11e8-91bd-cd4ac81054a2.png)
UGS Probe
In ugs, no error message comes, only by startup
Hope this helps?
The short issue for New HeigtMap comes soon

Greetings
Stefan

**Comment by martin2250** [comment]
sorry, did not mean to close this. I'll upload a new release now, please test if the error still occurs.
(also please excuse that this took so long, I never remembered to check this issue again)

**Comment by S2000Stefan** [comment]
Hi Martin,
sorry for the late Response. The issue for the "Received Bad Probe" are fixed. 
The issue can be Closed.
Now I can start building my Rotary Axis.   :)

**Comment by martin2250** [comment]
Hi Stefan,
I hope this wasn't the only reason holding you back so far, I'm looking forward to seeing some pics :wink: 

Cheers!
