### ISSUE TITLE
Comunicaron CNC -pc

### ISSUE THREAD

**Issue by ezequielbritos** [martin2250/OpenCNCPilot#68]
Hi. When I use OpenCNCpilot and I do the autolevel map rare characters appear in red. Those says something like : bad status received <idleMPos xxxxx?????????>

**Comment by martin2250** [comment]
Hi,
what version of grbl are you using? is it possible that the serial connection between the microcontroller and your PC isn't good and introduces errors?

**Comment by ezequielbritos** [comment]
Hi. My version is grbl 0.8. Is it possible to change it to grbl 0.9? If its
possible, would the outputs change (spindle motor , x axis, y axis, etc)?

**Comment by martin2250** [comment]
I'm sick of this, go read the description and figure it out yourself

**Comment by ezequielbritos** [comment]
Sory, I have version 0.9j not 0.8

El 15 sep. 2018 09:04, "Martin Pittermann" <notifications@github.com>
escribió:

I'm sick of this, go read the description and figure it out yourself

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/martin2250/OpenCNCPilot/issues/68#issuecomment-421559126>,
or mute the thread

**Comment by martin2250** [comment]
see 99a77a19092accad1c25ec156320e377859d3946

**Comment by deHarro** [comment]
Hi Martin,

aus meiner Erfahrung:
Schreibe nicht nur auf, was die Voraussetzungen sind, das reicht nicht :(

Schreibe explizit dazu, dass alle anderen/kleineren Versionen von GRBL NICHT funktionieren und es keinen workaround gibt!
(Vielleicht sogar noch explizit V0.8 und V0.9 und V1.0)

Ggf. das Gleiche für .NET

Gruß
Harald

[Bezug ist der Link aus dem letzten Post oben]

**Comment by martin2250** [comment]
Hi Harald,

habe auch schon überlegt das groß an den Anfang des Readmes zu schreiben, aber ich wollte nur ungern 'den ersten Eindruck versauen'. Und sind wir mal ehrlich, weiter als bis zum Screenshot werden viele nicht lesen, daher bringt das dahinten wahrscheinlich wenig (werd ich aber trotzdem mal hinzufügen, danke für den Tipp). Ich hoffe, die Issue-Vorlage bringt was, und wenn das nicht reicht, dann sind die angedrohten Konsequenzen, denke ich, gerechtfertigt :)

Grüße
Martin

**Comment by ezequielbritos** [comment]
Así como vos escribís en Alemán yo te escribo en Español. Mucho trabajo
parece responder de buena manera. Espero que cuando no entiendas algo no te
traten de niño por no saber sino que sean predispuestos a resolver tu duda.
Por último, mis dudas iban dirigidas a martín2550 no a vos, así que por
favor no te involucres en lo que no te corresponde. Gracias

**Comment by martin2250** [comment]
We were discussing the general issue of people not reading (or not understanding) my Readme, so @deHarro's comment was absolutely relevant, albeit not specific to your request.

Using outdated versions of grbl was the reason for probably 10% of all issues so far, which is the reason for my annoyed comment.

**Comment by deHarro** [comment]
Hi ezequielbritos,
sorry to offend you! 

I made the mistake to "answer" per mail program to the notification massage from github. 
I didn't realize, that this answer will be posted into your issue on github.
My answer was meant as personnel comment for Martin, we both live in Germany, so I used german as means of communication.

Harald
