### ISSUE TITLE
Connection 

### ISSUE THREAD

**Issue by Benjamincreator** [martin2250/OpenCNCPilot#7]
Hi Martin 

 When i went to connect to my Arduino Uno CNC shield with Open CNC Pilot i receive
'<idle|MPos:0.000,0.000,0.000|FS:0,0|Pn:XY>' in red text scrolling past on the App 

~Ben

**Comment by martin2250** [comment]
Hi,
OpenCNCPilot doesn't work with GRBL 1.1 for now. You can use the fork by @bytemaster-0xff or downgrade to 0.9 until I get around to update it

**Comment by martin2250** [comment]
Hi Ben,
I just released version 1.2, which supports grbl v1.1f
