### ISSUE TITLE
Warning message when loaded a new project needed

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#73]
Hi Martin,

I once again crashed my part after loading the next gcode file for another tool.

What happened?
OCP finishes the current job, moves to X0 Y0 Z5 and I change the bit.
Then I have to adjust the tool length by moving to Z0 (the only position I can rely on for that).
And now I forget that OCP thinks it is at Z5.

Next my mill rushes to the first coordinate where it dives at least 5 mm into the material to reach its Z0...

Now my proposal: 
When finishing a job and another job gets loaded please issue a messagebox which points out that Z is NOT Zero but something around 5 mm (or whatever one has defaultet to) and that the Z axis has to be zeroed again.

Since some guys may have no problem with such omissions, perhaps make it parametrizeable?

Thanks! 
Harald

**Comment by martin2250** [comment]
Hi Harald,

I don't quite understand your problem, do you put the next tool in the collet, pull it down until it touches the material and then tighten the collet?

Martin

**Comment by deHarro** [comment]
Hi Martin,
no. Would that be the correct procedure?
I suppose there are situations where the tool length are too different to succeed with this approach (but it can succeed I confess, at least when the tools are of approximately the same length).

I tighten the collet at the tool change position (which is somewhere above the current X+Y position) and then move Z down till the new tool touches the original Z=0 point.
The moves for that I perform with my joystick, so OCP does not know anything about it and has to learn the new zero Z.
Since I recently work with wood, I do zero Z by optical means and sometimes I forget to tell OCP that the tip is at zero (OCP has the info Z=5 from its last stop).

Harald

**Comment by martin2250** [comment]
Hi Harald,

no, that would be a horribly inaccurate way to set your tool length (at least for making PCBs, in wood you could get away with that, though the tool will lift a bit when you tighten the collet, say ~0.5mm).

Does the joystick bypass grbl entirely, eg. your steppers receive pulses from another controller? I'd strongly recommend against doing that as it will lead to incorrect machine coordinates, making machine limits ineffective.

I use M0 commands to remind me to check something. Eg. at the start of your file add an M0 and a comment with the reminder. I always do that at the start of potentially dangerous macros. Most CAM software should allow you to add a custom preamble to the nc file.

Martin

**Comment by deHarro** [comment]
Hi Martin,

yes, the steppers are driven by another controller when I use the joystick.
The mentioned problems where the reason for asking you to implement a second interface for my joystick (perhaps you remember... ;-)

You are right, EstlCam has the option to set user text as notification in the nc file.
I will try that. Thanks for the hint!

I'll close this issue.
Harald
