### ISSUE TITLE
Runtime display is not zeroed after loading a new job

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#74]
Hi Martin,

the display of passed time for the last job is not zeroed when a new file is loaded.

Harald

**Comment by martin2250** [comment]
Hi Harald,

thanks for the info, I'll fix that for the next release.

Martin

**Comment by martin2250** [comment]
I didn't get a chance to test it yet, if it still doesn't work just reopen this issue :)
