### ISSUE TITLE
Caption should display the currently loaded fielname

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#75]
Hi Martin,
I am recently working with many different files for one project and I found me puzzled when trying to memorize what file I have currently loaded in OCP.
One can see the name in the file window, but only if the generating tool enters the name into the file and only at the very beginning, if the job has not started.

It would be very helpful to have the filename displayed in the caption, as seen in all MS Apps.

Thanks!
Harald

**Comment by martin2250** [comment]
Hi Harald,

yes, that's a great addition. Thanks! 

Martin
