### ISSUE TITLE
In the New Height Map Window no point input

### ISSUE THREAD

**Issue by S2000Stefan** [martin2250/OpenCNCPilot#77]
Hi Martin,
as already written here the small Point issue in the New Height Map window.
If you try to enter a Point like 38.90 the result is:
![height map 1](https://user-images.githubusercontent.com/35189051/48218163-866b3e00-e389-11e8-9093-43cdffc8909c.png)
It is possible to edit the field with a point:
![height map](https://user-images.githubusercontent.com/35189051/48218257-c16d7180-e389-11e8-9590-2b73d30809c3.png)
Hope that helps as a memory support.   ;)
Greetings
Stefan

**Comment by martin2250** [comment]
Thanks for the reminder!
While I was at it, I also made it replace commas with dots, so we can use the numpad comma on our German keyboards :)

Greetings
Martin
