### ISSUE TITLE
Touch screen size buttons

### ISSUE THREAD

**Issue by beckmx** [martin2250/OpenCNCPilot#81]
Hello, firstly I want to congratulate you on the amazing work you have done here, I used chilippepr before and UGS but this has proven by far to be faster and since the beginning it created great work on the first try. I just would like to know if you can add a way to make buttons bigger, I was using a touch screen windows tablet and it is kind of difficult to click on the right button. But the rest is just great ;)

**Comment by martin2250** [comment]
Hi, thanks! Does changing the global Windows scalong factor work? You'd probably have to change it every time you want to use OCP, which would be annoying. I have used OCP on my 13.3" convertible at 100% global windows scale for three years now and I occasionally use the touchscreen. With 150% or even 200% the buttons should be large enough to replace the mouse completely.

I don't know if there is an easy way to implement different button sizes in WPF and I don't think it will be used enough to make it worth my time. You need a keyboard anyways for things like jogging and manual commands, so this already covers most devices as most keyboards on mobile devices have trackpads. 

That said, I'm still open to the idea, so if anyone here knows how to do this in WPF, feel free to implement it and send me a PR :)
