### ISSUE TITLE
Manually edit a point of surfacing

### ISSUE THREAD

**Issue by krtschmr** [martin2250/OpenCNCPilot#84]
![image](https://user-images.githubusercontent.com/13366714/49695095-0f170d00-fbc8-11e8-896a-7e98a5e66a50.png)

for whatever reason, one point is wrong and spiked up. is there a way to manually correct that one or smoothen the surface? i can't find such a feature and right now that means i need to rescan for 1.5 hours

**Comment by martin2250** [comment]
Hi,

you already closed this issue, did you find a solution by yourself? In any case the .hmap files are just plain xml files, you can edit all points in there.
