### ISSUE TITLE
extended help would be fine :)

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#87]
Hi Martin,
in every version of OCP I stumble over the same problem: I don't know, what the different G-Codes stand for you mention.
I then head into the net and search for a doc which explains waht G18/G19 may mean, start reading and reading (what machine is this given explanation meant for) and lose my focus :(

If you suddenly suffer from deadly dullness, you may implement some sort of quick help for g-codes, at least for those codes you utilize in your program or in your comments for new versions.

Just an idea... :)
Harald

**Comment by martin2250** [comment]
Hi Harald,

the best I could do would be to include a button that takes you to the [LinuxCNC quick reference](http://linuxcnc.org/docs/html/gcode.html), copying over all the explanations into OpenCNCPilot would
- slow down load times (a tiny bit)
- require me to search for LinuxCNC's license and check whether or not I'm even allowed to copy the text
- require levels of dullness that I haven't seen in a long time :D

In all seriousness though, the quick reference is pretty much already perfect in my opinion, just bookmark it on the PC that you use for OCP. I might add a button to the UI to save the click of opening the browser of choice.

Martin

**Comment by deHarro** [comment]
Accepted ;-) Link is placed. Thanks!
You already know that this was not meant really seriously, I hope.
Harald
