### ISSUE TITLE
Losing steps

### ISSUE THREAD

**Issue by canbaytok** [martin2250/OpenCNCPilot#88]
Hi there Martin!

I wanted to challenge myself and create a double sided PCB so I hooked up my CNC and started milling. After finishing the top layer and flipping the board I started the bottom layer job and left the machine running while I was gone. After I came back and cleaned the PCB a little I noticed these huge artifacts which look like the machine is losing steps:
![img_20181226_132059](https://user-images.githubusercontent.com/25607877/50445826-8c08ed00-0911-11e9-95df-de7149522be1.jpg)

A while ago I created my own arduino nano based CNC controller and I forgot the pull up resistors for the probe signal which causes OCP to randomly trigger a probe event when milling the PCB and I wanted to know if a probe event can cause loss of steps?

EDIT: I just remembered what might cause problems like this also. I installed TMC2100 stepper drivers for the X and Y axis, cause they are much much quieter and better than the standard chinese A4988 drivers, but last year I encountered the problem on my 3D printer that the stealthChop mode made the stepper motors lose steps. Maybe its a combination of probe triggering and the steppers driver. Guess I have to experiment a little *shrug*.

**Comment by canbaytok** [comment]
Alright I think i found the solution. The configuration of the tmc2100 isnt as straight forward as I thought and after half an hour I found the correct configuration technique which I will test tomorrow and close this issue when its resolved.

I will also mod my grbl controller to rule out the possibility that the probe triggering and OCPs handling of the probe event causes loss of steps.

**Comment by martin2250** [comment]
Hi,
yeah, this seems like driver problems. grbl shouldn't loose steps when it sees a probe signal. anyways, this is not an issue with OCP
