### ISSUE TITLE
negative values when probing are truncated

### ISSUE THREAD

**Issue by deHarro** [martin2250/OpenCNCPilot#90]
Hi Martin,
I thought I already created this issue, but obviously not. If so, I didn't find it...
Running OCP V1.5.4.0, probing PCB.

Negative values are truncated at the right edge of the surrounding rectangle (see left arrow)

![negative_values_cut_off_a](https://user-images.githubusercontent.com/26298406/51326409-5c13bc00-1a6f-11e9-9aca-16d917d8ac7a.JPG)

Probably same problem at right arrow?

Harald

**Comment by martin2250** [comment]
Hi Harald,

sure thing, I'll fix that before the next release. Thanks!

Martin
