### ISSUE TITLE
6-axis?

### ISSUE THREAD

**Issue by Denis13071981** [martin2250/OpenCNCPilot#94]
Hallo.
Do you considering 6-axis support?
For a project like 
https://github.com/yaroslavVl/6-AXIS-USBCNC-GRBL

**Comment by martin2250** [comment]
Hi Denis,
define 6-axis support. A while back I added a setting for Yaroslav to ignore A, B and C-axis positions for generating the 3D preview (#63 ). That way, you can send unmodified 6-axis gcode to grbl and at least have a preview of XYZ. There is no readout for ABC, so you can't see the current position of these axes.

As OpenCNCPilot was and still is mostly inteded for circuit board milling, I don't plan on adding 6-axis support. I might add readouts for A/B/C when I have some spare time, but it's not particularly high on my list.
