### ISSUE TITLE
Button for homing. Reset after alarm does not really work

### ISSUE THREAD

**Issue by microtronics** [martin2250/OpenCNCPilot#98]
I'm just getting up and running with my new CNC, but am quite used to similar stuff (3D printing).

So far, I think your software is the most pretty and usable tool to control a CNC! bCNC might have a bunch of extra features, but most of them aren't really necessary anyways.
I really miss the Homing button in OpenCNCpilot, though. I always have to type the $H manually. Adding custom buttons would also be great, but it's not that important.

Another thing I noticed: When doing a G38.2 probe with Z set too far the soft limits in GRBL trigger and throw an alarm. However, after pushing the Alarm/Idle button it is not possible to move the machine with i.e. jogging. I have to do a soft reset and home again, which is not really desired. Is there something I'm missing?

**Comment by martin2250** [comment]
Hi,
never added a homing button as it's only used once and not during operation, can't hurt though.

About your other issue: I'm not sure what causes this, but after a soft reset, you should be able to unlock grbl with $X. You can also try to flush the serial buffer by clicking on the progress bar in the machine tab, but this should be done automatically when pressing soft reset.
